### ISSUE TITLE
GR output columns

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/raer#59]
This is the current GR structure:

```
GRanges object with 45 ranges and 2 metadata columns:
                             seqnames    ranges strand |         Ref         Var
                                <Rle> <IRanges>  <Rle> | <character> <character>
    CHIKV_AF15561_762_- CHIKV_AF15561       762      - |           C          CT
    CHIKV_AF15561_773_- CHIKV_AF15561       773      - |           G          GT
   CHIKV_AF15561_1580_- CHIKV_AF15561      1580      - |           C          CT
   CHIKV_AF15561_2315_- CHIKV_AF15561      2315      - |           C          CT
   CHIKV_AF15561_2327_- CHIKV_AF15561      2327      - |           C          CT
                    ...           ...       ...    ... .         ...         ...
  CHIKV_AF15561_10408_- CHIKV_AF15561     10408      - |           C          CT
  CHIKV_AF15561_10409_- CHIKV_AF15561     10409      - |           C          CT
  CHIKV_AF15561_10446_+ CHIKV_AF15561     10446      + |           C          CT
  CHIKV_AF15561_10446_- CHIKV_AF15561     10446      - |           G          GA
  CHIKV_AF15561_11655_+ CHIKV_AF15561     11655      + |           T          TA
```

I would argue it's more useful to have  single-nucleotide `Ref` and `Alt` columns, keeping consistent with the VCF format. This would make computing e.g. ORF changes based on a single-nucleotide `Alt` easier (right now you have to change `CT` to `T` on the fly).

I would also suggest changing the values of `Var` from looking like a dinucleotide (`CT`) to make explicit it has the concept of a mutation (e.g., `C>T`). You could also eliminate this entirely as it's easy to compute from `Ref` and `Alt`.

**Comment by kriemo** [comment]
i agree, it makes sense to make the output more vcf-like. Additionally we should consider reporting distinct variants at the same site as separate records, which could simplify the other columns, as for most purposes we would only need to track counts of ref and alt.
