### ISSUE TITLE
functionality to examine expression of editing enzymes

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/raer#82]
Given an RSE or SCE and TxDb as input, examine:

1. expression levels of RNA editing enzymes (ADAR, possibly APOBEC)
2. gene ontology signatures, focused on sigaling pathways upstream of editing

Generate tidy tibbles and maybe a simple boxplot of gene expression (by cell type, for SCE).

**Comment by kriemo** [comment]
Implementing this would require a fair bit of code and would be hard to make robust across different species and gene naming conventions. I'm closing this for now but may reconsider at a later date.
